sed -i s@srss@flym@g app/src/main/java/net/frju/flym/service/FetcherService.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/service/AutoRefreshJobService.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/dao/EntryDao.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/dao/FeedDao.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/dao/TaskDao.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/AppDatabase.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/entities/Entry.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/entities/SearchFeedResult.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/entities/EntryWithFeed.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/entities/FeedWithCount.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/entities/Task.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/entities/Feed.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/converters/Converters.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/data/utils/PrefConstants.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/usage/UsageActivity.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/settings/SettingsActivity.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/settings/SettingsFragment.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/entries/EntriesFragment.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/entries/EntryAdapter.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/about/AboutActivity.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/discover/DiscoverActivity.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/discover/SquareGridItemLayout.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/discover/FeedSearchFragment.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/discover/DiscoverFragment.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/discover/FeedManagementInterface.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/views/AutoSummaryListPreference.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/views/DragNDropListener.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/views/EmptyRecyclerView.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/views/DragNDropRecyclerView.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/feeds/FeedListEditActivity.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/feeds/EditFeedAdapter.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/feeds/BaseFeedAdapter.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/feeds/FeedListEditFragment.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/feeds/FeedGroup.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/feeds/DrawerFeedAdapter.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/main/MainNavigator.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/main/ContainersLayout.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/main/MainActivity.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/entrydetails/EntryDetailsView.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/entrydetails/EntryDetailsActivity.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/ui/entrydetails/EntryDetailsFragment.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/MyAppGlideModule.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/utils/ActivityExtensions.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/utils/ContextExtensions.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/utils/ViewExtensions.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/utils/StringExtensions.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/utils/HtmlUtils.kt
sed -i s@srss@flym@g app/src/main/java/net/frju/flym/App.kt
